name: deploy
on:
  push:
  branches: [ main ]

  workflow_dispatch:

    jobs:
  build:
    runs-on: ubuntu-latest
steps:
      - uses: actions/checkout@main
- name: Upload to S3
        run: |
          aws s3 mb s3://spanishjourney
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
